name: Test package

on:
  push:
    # The CI is executed on every push on every branch
    branches:
      - main
  pull_request:
    # The CI is executed on every pull request to the main branch
    branches:
      - main

  schedule:
    # The CI is executed every day at 8am
    - cron: "0 8 * * *"

  runs-on: ubuntu-22.04
  container: ghcr.io/fenics/dolfinx/dolfinx:nightly

jobs:
  test-code:
    steps:
      - uses: actions/checkout@v3

      - name: Install package
        run: python3 -m pip install .[test]

      - name: Run tests
        run: python -m pytest 